paths:
  /api/:
    get:  
      summary: Todos los productos
      tags:
        - Productos
      responses:
        '200':
          description: Se reciben todos los productos
        '500':
          description: Controller No se pudo obtener los productos.
  /api/{pid}:
    get:  
      summary: El producto por ID
      tags:
        - Productos
      parameters: 
        - name: pid
          required: true
          in: path
          description: ID del producto alojado en la base de datos
          schema: 
            type: string
      responses:
        '200':
          description: Se recibe el producto por su ID
        '500':
          description: Controller No se encontro el producto por ID.
    put:  
      summary: Actualiza un producto por ID
      tags:
        - Productos
      parameters: 
        - name: pid
          required: true
          in: path
          description: ID del producto alojado en la base de datos
          schema: 
            type: string
      responses:
        '200':
          description: Controller Producto actualizado con éxito
        '404':
          description: Controller No se encontro el producto con el ID:${pid}
        '500':
          description: Controller Error al actualizar el producto
    delete:  
      summary: Elimina un producto por ID
      tags:
        - Productos
      parameters: 
        - name: pid
          required: true
          in: path
          description: ID del producto alojado en la base de datos
          schema: 
            type: string
      responses:
        '200':
          description: "Controller: Producto eliminado con éxito"
        '404':
          description: Controller No se encontro el producto con el ID:${pid}
        '500':
          description: "Controller: Error del servidor al eliminar el producto"
  /api/create:
    post:  
      summary: Crear un producto
      tags:
        - Productos
      responses:
        '201':
          description: Controller Producto creado con éxito
        '500':
          description: Controller Error al crear el producto
components: 
  schemas: 
    products: 
      type: object
      properties: 
        _id: 
          type: ObjectId
          description: ID generado automaticamente por Mongo
        title:
          type: string
          description: Titulo del film
        description:
          type: string
          description: Descripcion del film
        code:
          type: string
          description: Codigo de producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Disponibilidad
        stock:
          type: number
          description: Cantidad en stock
        category:
          type: string
          description: Categoria del film
        thumbnails:
          type: string
          description: Poster del film
      example: 
        _id: 64d2f3a9b1c4e5f6a7b8c9d0
        title: Hot Fuzz
        description: Hot Fuzz es una comedia de acción británica donde un policía demasiado eficiente es trasladado a un tranquilo pueblo que esconde un oscuro ysangriento secreto.
        code: aaa
        price: 3500
        status: true
        stock: 12
        category: Accion
        thumbnails: https://m.media-amazon.com/images/I/71M6PLW0yxL.jpg